# Generated by Django 5.0.6 on 2024-06-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_photo",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
