# Generated by Django 5.0.6 on 2024-06-11 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_customuser_bio_customuser_profile_photo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chirp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chirp", models.TextField(blank=True, max_length=1000, null=True)),
                ("tweeted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tweeted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
