# Generated by Django 5.0.6 on 2024-06-11 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_chirp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chirp",
            old_name="tweeted_by",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="chirp",
            old_name="tweeted_at",
            new_name="created",
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chirp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.chirp"
                    ),
                ),
            ],
        ),
    ]
