# Generated by Django 5.0.6 on 2024-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_chirp_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="chirp",
            name="tags",
        ),
        migrations.AddField(
            model_name="chirp",
            name="tags",
            field=models.ManyToManyField(blank=True, to="base.tag"),
        ),
    ]
