# Generated by Django 5.0.6 on 2024-06-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_tag_remove_chirp_tags_chirp_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chirp",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
